apiVersion: v1
kind: Service
metadata:
  name: queue
spec:
  selector:
    app: queue
  ports:
    - name: endpoint
      port: 5672

    - name: http
      port: 15672
      nodePort: 30672

  type: NodePort
